language: node_js
node_js:
  - 6
branches:
  only:
    - master
notifications:
  email:
    - vitaliy.kuznetsov@yahoo.co.uk
script: ./deploy.sh
env:
  global:
    secure: P/pXrNpgczaxI1KeZDpljM98Rhw64wtGG2N0xQHO1NVlMMeVDJdyr3D1ktMaBJKQUAGq3CNHEC4F8TWg25Fi+z/vsqecYnE6zWuzYdN7iRf9y4zM1hdGpxQxSb0KFJRwdjoKv8xW94w2gWMd0uL6kv6/5MNa62uc1UNeTFgZazJSW0njUSgQC8HArdpQKdFUh0qqn9lsqDOUuOBzUzmOVKA0Q6NUftvS1lHHNUBdg6+tmQ7Pvr0FGtsjyjV9JzAXgZh/wZwHQ5QYPBxMQderauW/ALDFxA0XjJu/HZgMTgcW7YA5cmbAstJr0FDvJdD+CdR5l/7T5KZJlA7awqKyWoU1fGZzZq196BS/AXomd5v0YUYzqAa7jjdmXGBJmfpvqzMeZ+4m7c2UmD33vdn368yXPG0x2difDrbNkn+qTqFyaD0nDdBHcGXMCdxoV7PRx65pSAhiB3znHkcMNQ2f/l5yZeEAqWzsdQIUqvM44OYVNmNIPOaGLAC07KyVwljvOLUgToHc6bSOZDbGDVy3qOdFDI4yT5P+P2mg7XGtXKPAtCTDXTCT9ACECwiL2UfjGTfPow+co+TqPiBhogrI6hNNmTVgi6DT+Ogg7QB6QLy0IVwNlsOcwvHqtAJ3lwOJaFsN+SdebO94zzPMxeIy/LtYwsdN/2UEUSoGo8eCeWw=
